# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-09 01:31
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(default='Untitled', max_length=100)),
                ('description', models.TextField()),
                ('section_type', models.CharField(choices=[('RECT', 'Rectangular'), ('CIRC', 'Circular'), ('T', 'T'), ('I', 'I'), ('U', 'U')], max_length=20)),
                ('concerte_class', models.CharField(choices=[('C15_20', 'C15/20'), ('C20_25', 'C20/25'), ('C25_30', 'C25/30'), ('C30_35', 'C30/35')], max_length=20)),
                ('steel_class', models.CharField(choices=[('S235', 'S235'), ('S275', 'S275'), ('S355', 'S355'), ('S420', 'S420')], max_length=20)),
                ('limit_state', models.CharField(choices=[('ULTIMATE', 'Ultimate'), ('SERVICE', 'Service')], max_length=20)),
                ('height', models.FloatField(null=True)),
                ('width', models.FloatField(null=True)),
                ('diameter', models.FloatField(null=True)),
                ('bw', models.FloatField(null=True)),
                ('hf', models.FloatField(null=True)),
                ('hf1', models.FloatField(null=True)),
                ('hf2', models.FloatField(null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
