# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-10 02:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sections', '0002_auto_20151210_0123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='concerte_class',
            field=models.CharField(choices=[('C15_20', 'C15/20'), ('C20_25', 'C20/25'), ('C25_30', 'C25/30'), ('C30_35', 'C30/35')], default='C15_20', max_length=20),
        ),
        migrations.AlterField(
            model_name='section',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='section',
            name='limit_state',
            field=models.CharField(choices=[('ULTIMATE', 'Ultimate'), ('SERVICE', 'Service')], default='ULTIMATE', max_length=20),
        ),
        migrations.AlterField(
            model_name='section',
            name='section_type',
            field=models.CharField(choices=[('RECT', 'Rectangular'), ('CIRC', 'Circular'), ('T', 'T'), ('I', 'I'), ('U', 'U')], default='RECT', max_length=20),
        ),
        migrations.AlterField(
            model_name='section',
            name='steel_class',
            field=models.CharField(choices=[('S235', 'S235'), ('S275', 'S275'), ('S355', 'S355'), ('S420', 'S420')], default='S235', max_length=20),
        ),
    ]
