# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-10 03:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sections', '0003_auto_20151210_0237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='height',
            field=models.FloatField(default=400, null=True),
        ),
        migrations.AlterField(
            model_name='section',
            name='width',
            field=models.FloatField(default=200, null=True),
        ),
    ]
