# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-15 23:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sections', '0008_auto_20151215_2239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='steel_class',
            field=models.CharField(choices=[('A400', 'A400'), ('A%00', 'A500')], default='A%00', max_length=20),
        ),
    ]
