# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-26 02:01
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sections', '0010_auto_20151215_2315'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='section',
            name='bw',
        ),
        migrations.RemoveField(
            model_name='section',
            name='diameter',
        ),
        migrations.RemoveField(
            model_name='section',
            name='height',
        ),
        migrations.RemoveField(
            model_name='section',
            name='hf',
        ),
        migrations.RemoveField(
            model_name='section',
            name='hf1',
        ),
        migrations.RemoveField(
            model_name='section',
            name='hf2',
        ),
        migrations.RemoveField(
            model_name='section',
            name='limit_state',
        ),
        migrations.RemoveField(
            model_name='section',
            name='width',
        ),
        migrations.AddField(
            model_name='section',
            name='geometry',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={'height': 0.4, 'width': 0.2}),
        ),
    ]
