# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-09 17:37
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sections', '0011_auto_20151226_0201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='geometry',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={'bw': 0.1, 'diam': 0.4, 'height': 0.4, 'hf': 0.1, 'hf1': 0.1, 'hf2': 0.1, 'width': 0.2}),
        ),
    ]
