# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-16 12:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sections', '0013_auto_20160109_1955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='concerte_class',
            field=models.CharField(choices=[('C12_15', 'C12/15'), ('C16_20', 'C16/20'), ('C20_25', 'C20/25'), ('C25_30', 'C25/30'), ('C30_37', 'C30/37'), ('C35_45', 'C35/45'), ('C40_50', 'C40/50'), ('C45_55', 'C45/55'), ('C50_60', 'C50/60'), ('C55_67', 'C55/67'), ('C60_75', 'C60/75'), ('C70_85', 'C70/85'), ('C80_95', 'C80/95'), ('C90_105', 'C90/105')], default='C20_25', max_length=20),
        ),
    ]
