# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-16 18:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sections', '0014_auto_20160116_1204'),
    ]

    operations = [
        migrations.RenameField(
            model_name='section',
            old_name='concerte_class',
            new_name='concrete_class',
        ),
    ]
